version: '3.8'

networks:
  fdr:
    external: true

services:
  fdr_db:
    image: postgres:16
    container_name: fdr_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fdr

  fdr_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fdr_api
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - fdr_db
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - MERCADO_PAGO_ACCESS_TOKEN=${MERCADO_PAGO_ACCESS_TOKEN}
    command: ["python", "run.py"]
    networks:
      - fdr
    
    

volumes:
  postgres_data:
